api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:   ['application/ld+json','application/json+ld']
        jsonhal:  ['application/hal+json','application/json+hal']
        jsonapi:  ['application/vnd.api+json','application/json+vnd.api']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml', 'text/yaml']
        csv:      ['text/csv']
        html:     ['text/html']
        pdf:      ['application/pdf']
        docx:     ['application/vnd.ms-word', 'application/vnd.openxmlformats-officedocument']
