apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-creation-service.fullname" . }}
  labels:
    {{- include "document-creation-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "document-creation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "document-creation-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "document-creation-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: dependencies
          secret:
            secretName: {{ include "document-creation-service.fullname" . }}-dependencies
            defaultMode: 420
        {{- if .Values.fixtures }}
        - name: fixtures
          configMap:
            name: {{ include "document-creation-service.fullname" . }}-fixtures
            defaultMode: 420
        {{- end }}

      containers:
        - name: {{ include "document-creation-service.fullname" . }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /srv/api/config/packages/dependencies.yaml
              subPath: dependencies.yaml
              name: dependencies
              readOnly: true
            {{- if .Values.fixtures }}
            - mountPath: /srv/api/fixtures
              name: fixtures
              readOnly: true
            {{- end }}
          env:
            - name: APP_ENV
              value: {{ .Values.config.env }}
            - name: AUTH_ENABLED
              value: 'true'
            - name: APP_REPRO
              value: 'https://github.com/ConductionNL/document-creation-service'
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: trusted-hosts
                  name: {{ include "document-creation-service.fullname" . }}
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  key: trusted-proxies
                  name: {{ include "document-creation-service.fullname" . }}
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  key: app-cors-allow-origin
                  name: {{ include "document-creation-service.fullname" . }}
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: app-version
                  name: {{ include "document-creation-service.fullname" . }}
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: {{ include "document-creation-service.fullname" . }}
            - name: APP_CACHE
              valueFrom:
                configMapKeyRef:
                  key: cache
                  name: {{ include "document-creation-service.fullname" . }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: {{ include "document-creation-service.fullname" . }}
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ include "document-creation-service.fullname" . }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redis-host
                  name: {{ include "document-creation-service.fullname" . }}
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: redis-port
                  name: {{ include "document-creation-service.fullname" . }}
            {{- end }}
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
        - name: {{ include "document-creation-service.fullname" . }}-nginx
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          env:
            - name: PHP_SERVICE
              value: localhost
            - name: NGINX_HOST
              value: localhost
            - name: BACKENDS
              value: localhost
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /api
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
