{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-creation-service.fullname" . }}
  labels:
  {{- include "document-creation-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=11" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else if .Values.postgresql.url  }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ else }}
  database-url:
  {{ end }}
  app_application_key: {{ .Values.security.applicationKey | b64enc | quote }}
